[package]
name = "kafjisho-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.4"
axum-extra = "0.10.1"
cookie = "0.18.1"
async-trait = "0.1.88"
tokio = { version = "1.45.1", features = ["full"] }
tower-http = { version = "0.6.6", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
chrono = { version = "0.4.41", features = ["serde"] }
diesel = { version = "2.2.11", features = [
    "postgres",
    "serde_json",
    "chrono",
    "r2d2",
    "uuid",
] }
dotenvy = "0.15.7"
anyhow = "1.0.98"
argon2 = "0.5.3"
rand = "0.8.5"
jsonwebtoken = { version = "9.3.1", default-features = false }
uuid = { version = "1.17.0", features = [
    "v4",                
    "fast-rng",         
    "macro-diagnostics",
    "serde",
] }
